### ISSUE TITLE
[Bug] Metronome Stops when Scroll on long Notes [0.2.0]

### ISSUE THREAD

**Issue by FelipeRearden** [curtgrimes/obsidian-metronome-plugin#1]
Hello @curtgrimes !!!!

## Nice to meet you !

I just wanna introduce myself and say thank you for creating this. A metronome in Obsidian is soothing that I have been dreaming since I start using Obsdian.

When I saw your repo I could believe that it is happening :)

I'm not a musician or anything related but I like to listen to metronome when I want to concentrate for reading, writing, doing math and thinking about something important. Forgive if I say something dumb or if I made a FR that is not fit into your plugin :) 
- I'm just trying to use metronome into all my Obsidian workflows

Thanks again for making this amazing plugin !!!!!!!!!

## My Bug Report 
I think I found a minor bug. When I have a note that is long (300/500 lines) the metronome stops working when I scroll to the end of the note.

When I go back to the top (which the metronome is located) its working again :)

Thanks for reading this!

Have a great day!

**Comment by curtgrimes** [comment]
Hi @FelipeRearden! I'm glad you are enjoying this plugin so far.

You are correct -- this is a bug. This is a consequence of how the metronome timer works, where it only ticks in response to the [`animationiteration`](https://github.com/curtgrimes/obsidian-metronome-plugin/blob/master/src/components/Metronome.vue#L67) event when the CSS animation does a cycle. If the element isn't visible on the screen, the CSS animation apparently isn't running.  I believe I can fix this by switching to use a more typical `setInterval` instead. I'll fix this in the next release.

**Comment by FelipeRearden** [comment]
Hello @curtgrimes !!!!

Thanks for the reply :)

Okay! Thanks for trying to "fix" this behavior! I wish the best luck 🍀 🍀 🍀 


Have a great day!!!!!!

**Comment by curtgrimes** [comment]
@FelipeRearden This should be fixed in [0.3.0](https://github.com/curtgrimes/obsidian-metronome-plugin/releases/tag/0.3.0). Please upgrade and let me know if you still have an issue with this. Thanks!

**Comment by FelipeRearden** [comment]
Hello @curtgrimes !!!!!

Thank you very much !!!!!!!!

Working perfect on version `0.3.0`  Obsidian `0.13.14` 

Have a great day!!!!!
