### ISSUE TITLE
[Feature Request] Metronome on Sidenotes

### ISSUE THREAD

**Issue by FelipeRearden** [curtgrimes/obsidian-metronome-plugin#2]
Hello @curtgrimes !!!!

I have a FR based on my workflow that I want to use with this amzing plugin :)

## My Workflow

I use notes inside the right sidebar with a list of musics to play while I´m working on Obsidian.

![0](https://user-images.githubusercontent.com/85180696/147133008-54d78b86-869c-48be-a2c4-9b35395f3dfd.png)

![2](https://user-images.githubusercontent.com/85180696/147133068-1dae67f7-1092-461e-b173-9331d8fb1867.png)

I choose the music that I want than I close the sidebar (THE MUSIC IS PLAYING WHILE THE SIDEBAR IS CLOSED)

![1](https://user-images.githubusercontent.com/85180696/147133036-b7a81edc-8e52-49f7-b859-35c6cd32b385.png)

I have a hotkey to quickly open and close the right sidebar 

## My FR

I want to add a metronome inside this audio Sidenote the same way that I have my other audio sources.

But when I close the right sidebar Metronome stops playing :(

![3](https://user-images.githubusercontent.com/85180696/147133139-71b75c0d-3e49-42d8-957e-edaf9822caba.png)

I don´t know if it is feasible but would be amazing if my metronome keep playing while the sidebar is closed(hide) the same way that my other audio musics does.

---

Forgive me if is something not related for musicians but I think could be a good Feature because we could keep one (or more than one) metronome for all notes in the vault instead of having to add a metronome for every note in the vault :)

Thanks for reading this!

Have a great day!

**Comment by curtgrimes** [comment]
I like this idea, this should be doable.

**Comment by FelipeRearden** [comment]
> I like this idea, this should be doable. 

I'm glad that you liked !!!!!!!!!! 

I wish you good luck !!!!

It's gonna be amazing for my workflow :)

**Comment by curtgrimes** [comment]
This will be available in a new release shortly. I'm making "keep playing in sidebar" the default behavior to match the behavior of media playing in a sidebar already like you pointed out.

**Comment by curtgrimes** [comment]
https://github.com/curtgrimes/obsidian-metronome-plugin/releases/tag/0.3.1

**Comment by FelipeRearden** [comment]
> This will be available in a new release shortly. I'm making "keep playing in sidebar" the default behavior to match the behavior of media playing in a sidebar already like you pointed out.

> https://github.com/curtgrimes/obsidian-metronome-plugin/releases/tag/0.3.1

Hello @curtgrimes !!!!!!!!!

Fantastic !!!!! Thank you very much !!!!

I'm so happy !!!!!!

It's working perfect on version `0.3.1` on Obsidian `0.13.14`
- Editor Legacy
- Live Preview

I wish you a fantastic day!!!!!!
