### ISSUE TITLE
[FR] Add an optional duration

### ISSUE THREAD

**Issue by whitenoisedev** [curtgrimes/obsidian-metronome-plugin#6]
Hi, 

I really appriciate the work you did with this plugins. I would like to use it as a periodic reminder to stay focused (currently use an app on my phone for this). 
Can you add a `duration: x` parameter so that the metronome automatically stops after x minutes?

Thanks for your work!

**Comment by FelipeRearden** [comment]
+1 fantastic idea :)

**Comment by curtgrimes** [comment]
I like this idea too. Often when I use the metronome I only need it when I’m starting off the song so some kind of parameter for automatically stopping it after a period of time would be indeed helpful.

**Comment by curtgrimes** [comment]
Added in 4d1fa91b2b37d4ebc7549f16b9c95b07f15b52aa and released in [0.8.0](https://github.com/curtgrimes/obsidian-metronome-plugin/releases/tag/0.8.0). Please update obsidian-metronome-plugin in Obsidian to use this new feature. Thanks!

**Comment by whitenoisedev** [comment]
works great!
