### ISSUE TITLE
Styles and pulsing doesn't work

### ISSUE THREAD

**Issue by NomarCub** [curtgrimes/obsidian-metronome-plugin#7]
![Animation](https://user-images.githubusercontent.com/5298006/150641109-907c27ea-f9b1-4900-8928-cf1898e64d34.gif)

I'm on 0.8.0 of the plugin, Obsidian v0.13.19, Windows 10.

**Comment by curtgrimes** [comment]
Can reproduce. Not limited to Windows. Happens when running more than one instance of a metronome on a page in live ~~edit~~ reading mode. Looking for a solution...

**Comment by curtgrimes** [comment]
This should be fixed in [0.8.1](https://github.com/curtgrimes/obsidian-metronome-plugin/releases/tag/0.8.1).

For your last metronome example, `style: dot` should be `style: dots` instead and it should work.

Please let me know if you are still having issues. Thank you!

**Comment by NomarCub** [comment]
I updated to 0.8.1, and the problem persists.

![Animation](https://user-images.githubusercontent.com/5298006/150674603-27d1a6aa-3b04-426e-bf88-de07a6f637d5.gif)

**Comment by NomarCub** [comment]
I had the latest Obsidian version, but updated from an old installer. A complete reinstall was needed, for anyone with similar problems.
